version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.11.2
    restart: always
    #command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}

  app:
    image: nextcloud:fpm
    restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_HOST: ${MARIADB_ROOT_HOST}

  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    links:
      - app
    #volumes:
    #  - /home/thrane/nextcloud-fpm/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app